server:
  port: 9090

spring:
  datasource:
    # url: jdbc:mysql://localhost:3307/hackathon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://172.17.0.1:3307/hackathon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false  # H2 비활성화

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format_sql: true

    app:
  jwt:
    secret: TEST_ONLY_SUPER_LONG_SECRET_KEY_AT_LEAST_32_BYTES_ABCDEFGH_1234567890
    access-token-validity-seconds: 7200
    
