server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hackathon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: hackathon
    password: 1125
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false  # H2 비활성화

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format_sql: true

    app:
  jwt:
    secret: TEST_ONLY_SUPER_LONG_SECRET_KEY_AT_LEAST_32_BYTES_ABCDEFGH_1234567890
    access-token-validity-seconds: 7200
    
    # 업로드 저장 루트 (배포할 때 변경할 곳)
  upload:
    base-dir: C:\Users\SamSung\OneDrive - inu.ac.kr\문서\대학교 강의자료\3학년 1학기\멋쟁이사자처럼 동아리\hackathon\receipts

clova:
  ocr:
    url: "https://6ub5hbkrwr.apigw.ntruss.com/custom/v1/45351/052f462209b7ff5e6202c6210292b33d5591684185839f2274abeca506ce4dfb/general"
    secret: "ZEtMUGZMenJ2TUFKTmJ5ck1JS2laaUxLeGRKcXNjSXc="