server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3307/hackathon?useSSL=false&allowPublicKeyRetrieval=true&defaultAuthenticationPlugin=com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin&authenticationPlugins=com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin,com.mysql.cj.protocol.a.authentication.MysqlNativePasswordPlugin&disabledAuthenticationPlugins=auth_gssapi_client,com.mysql.cj.protocol.a.authentication.OAuthAuthenticationPlugin"
    username: hackathon
    password: 1125

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clova:
  ocr:
    # 사용 중이면 값 채우기 / 당장 비활성화하려면 enabled:false만 남겨도 됨
    enabled: true
    url: "https://naveropenapi.apigw.ntruss.com/custom/v1/xxx/yyy/general"
    secret: "YOUR_X_OCR_SECRET"
    api-key: "YOUR_API_KEY"
