server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hackathon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false  # H2 비활성화

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format_sql: true
    
