server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  # 업로드 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  jwt:
    secret: TEST_ONLY_SUPER_LONG_SECRET_KEY_AT_LEAST_32_BYTES_ABCDEFGH_1234567890
    access-token-validity-seconds: 7200

  # 업로드 저장 루트 (배포할 때 변경할 곳)
  upload:
    base-dir: /home/ec2-user/uploads/receipts

clova:
  ocr:
    url: "https://6ub5hbkrwr.apigw.ntruss.com/custom/v1/45351/052f462209b7ff5e6202c6210292b33d5591684185839f2274abeca506ce4dfb/general"
    secret: "ZEctMUGZMenJ2TUFKTmJ5ck1JS2laaUxLeGRKcXNjSXc="
