name: Deploy to EC2

on:
  push:
    branches:
      - main  # 또는 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Connect & deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker stop hackathon-container || true
          sudo docker rm hackathon-container || true
          sudo docker pull heui0716/hackathon
          sudo docker run -d --restart=always -p 9090:9090 --name hackathon-container heui0716/hackathon
          sudo docker ps -a
